[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; connect-src 'self'; font-src https://fonts.gstatic.com; img-src 'self' data: *.example.com https://www.google-analytics.com/collect; object-src 'none'; script-src 'unsafe-inline'; script-src-elem 'unsafe-inline' 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; prefetch-src 'self'"  
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"
    X-XSS-Protection = "1; mode=block"