backend:
  name: github
  repo: BostoenToby/vital-cities-beweegscan
  branch: dev

media_folder: static/assets
public_folder: /assets

collections:
  - name: Header
    label: Header
    folder: src/cms/header
    create: true
    fields:
      - { name: ambition, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: title, label: Titel }
      - { name: subtitle, label: Subtitels }
      - { name: image, label: Foto, widget: image }

  - name: Probleem
    label: Probleem
    folder: src/cms/problem
    create: true
    fields:
      - { name: ambition, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: text, label: Tekst }
      - { name: boldpart, label: Tekst vetjes}

  - name: Waarom
    label: Waarom oplossen?
    folder: src/cms/waaromopl
    create: true
    fields:
      - { name: ambition, label: Ambitie, widget: select, multiple: false, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: text, label: Tekst, widget: markdown }

  - name: Hoe
    label: Hoe oplossen?
    folder: src/cms/hoeopl
    create: true
    fields: 
      - { name: ambition, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: text, label: Tekst, widget: markdown }

  - name: IntBron
    label: Interessante bronnen
    folder: src/cms/intbron
    create: true
    fields:
      - { name: ambition, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: title, label: Titel }
      - { name: link, label: Link }
      - { name: text, label: Tekst, widget: markdown }

  - name: GoodPractices
    label: Good Practices
    folder: src/cms/goodprac
    create: true
    fields:
      - { name: ambition, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: title, label: Title}
      - { name: image, label: Image, widget: image }
      - { name: date, label: Datum, widget: datetime }
      - { name: themes, label: Thema's}
      - { name: text, label: Tekst, widget: markdown}
      - { name: extra, label: Extra, widget: markdown }
