backend:
  name: github
  repo: BostoenToby/vital-cities-beweegscan
  branch: dev

media_folder: src/images
public_folder: /assets

collections:
  - name: Header
    label: Header
    folder: src/cms/header
    create: true
    fields:
      - { name: ambition, label: Ambitie, widget: select, multiple: false, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: title, label: Titel }
      - { name: subtitle, label: Subtitels }
      - { name: image, label: Foto, widget: image }
      - { name: tag, label: Tag }

  - name: Probleem
    label: Probleem
    folder: src/cms/problem
    create: true
    fields:
      - { name: ambitions, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: text, label: Tekst }
      - { name: boldpart, label: Tekst vetjes}

  - name: Waarom
    label: Waarom oplossen?
    folder: src/cms/waaromopl
    create: true
    fields:
      - { name: ambitions, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: text, label: Tekst, widget: markdown }

  - name: Hoe
    label: Hoe oplossen?
    folder: src/cms/hoeopl
    create: true
    fields: 
      - { name: ambitions, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: text, label: Tekst, widget: markdown }

  - name: IntBron
    label: Interessante bronnen
    folder: src/cms/intbron
    create: true
    fields:
      - { name: ambitions, label: Ambitie, widget: select, multiple: true, options: ["Actief bewegen en verplaatsen", "Verbonden stadskern", "Aantrekkelijke en veilige wandel- en fietsroutes", "Stad en buurt als sportplein", "Stad en buurt als speelplein", "Stad en buurt als ontmoetingsplek", "Bruikbaar, gevarieerd en voldoende groen"] }
      - { name: title, label: Titel }
      - { name: link, label: Link }
      - { name: text, label: Tekst, widget: markdown }

  - name: GoodPractices
    label: Good Practices
    folder: src/cms/goodprac
    create: true
    fields:
      # - name: thema
      #   label: Thema
      #   widget: select
      #   multiple: true
      #   options:
      #     - { label: "Actief bewegen en verplaatsen", value: "Actief bewegen"}
      #     - { label: "Verbonden stadskern", value: "verbonden stadskern"}
      - { name: thema, label: Thema, widget: select, multiple: true, options: 
          [{ label: "Actief bewegen en verplaatsen", value: "actief bewegen"},
          { label: "Verbonden stadskern", value: "verbonden stadskern"},
          { label: "Aantrekkelijke en veilige wandel- en fietsroutes", value: "fiets- en wandelroutes"},
          { label: "Stad en buurt als sportplein", value: "sporten"},
          { label: "Stad en buurt als speelplein", value: "spelen"},
          { label: "Stad en buurt als ontmoetingsplek", value: "ontmoeten"},
          { label: "Bruikbaar, gevarieerd en voldoende groen", value: "groen"},
          { label: "Technologie/data", value: "technologie/data"},
          { label: "Transversaal beleid", value: "transversaal"},
          { label: "Participatie & inspraak", value: "participatie"}]
       }
      - { name: title, label: Title}
      - { name: image, label: Image, widget: image }
      - { name: date, label: Datum, widget: datetime }
      - { name: text, label: Tekst, widget: markdown}
      - { name: warning, label: Warning, widget: markdown, optional: true}
