backend:
  name: github
  repo: BostoenToby/vital-cities-beweegscan
  branch: dev

media_folder: static/assets
public_folder: /assets

collections:
  - name: Waarom
    label: Waarom oplossen?
    folder: src/WaaromOpl
    create: true
    fields:
      - { name: ambition, label: Ambitie }
      - { name: text, label: Tekst, widget: markdown }

  - name: Hoe
    label: Hoe oplossen?
    folder: src/HoeOpl
    create: true
    fields: 
      - { name: ambition, label: Ambitie }
      - { name: text, label: Tekst, widget: markdown }

  - name: IntBron
    label: Interessante bronnen
    folder: src/IntBron
    create: true
    fields:
      - { name: title, label: Titel }
      - { name: link, label: Link }
      - { name: text, label: Tekst, widget: markdown }

  - name: GoodPractices
    label: Good Practices
    folder: src/GoodPrac
    create: true
    fields:
      - { name: title, label: Title}
      - { name: themes, label: Thema's}
      - { name: text, label: Tekst, widget: markdown}
      - { name: extra, label: Extra, widget: markdown }
      - { name: date, label: Datum, widget: datetime }
